apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: operations
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: operations
    server: https://kubernetes.default.svc
  - namespace: istio-system
    server: https://kubernetes.default.svc    
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'