apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: operations
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: istio-system
    server: https://kubernetes.default.svc    
  - namespace: vault
    server: https://kubernetes.default.svc   
  - namespace: keycloak
    server: https://kubernetes.default.svc            
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'
  