apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: vault-access-definitions
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: vault-access-definitions
    server: https://kubernetes.default.svc  
  orphanedResources:
    warn: false
  sourceRepos:
  - '*'