apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager 
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: cert-manager 
  source:
    helm:
      version: v3
      valueFiles:
      - values.yaml
      - values-security-{{ .Values.env }}.yaml
    path: helm-charts/cert-manager
    repoURL: https://github.com/paas2/cert-manager.git 
    targetRevision: HEAD
    
  destination:
    namespace: cert-manager 
    server: {{ .Values.spec.destination.server }}

  syncPolicy:
    syncOptions:
    - CreateNamespace=true  
    automated:  
      prune: true 

