apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-istio
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"   
spec:

  project: vault
  
  source:
    helm:
      version: v3
      valueFiles:
      - values.yaml
    path: helm-charts/vault-istio
    repoURL: https://github.com/paas2/vault.git 
    targetRevision: HEAD

  destination:
    namespace: vault
    server: {{ .Values.spec.destination.server }}
        
  syncPolicy:
    # syncOptions:
    # - CreateNamespace=true   
    automated:  
      prune: true             